# Generated by Django 3.2.3 on 2021-06-04 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libercom', '0003_auto_20210604_0016'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizz',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='Nome'),
        ),
    ]
