# Generated by Django 3.2.3 on 2021-06-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libercom', '0004_quizz_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='testemunho',
            name='enable',
            field=models.BooleanField(default=True),
        ),
    ]
