# Generated by Django 3.2.3 on 2021-06-05 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libercom', '0007_auto_20210605_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plano',
            name='icon',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Icone'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='name',
            field=models.CharField(max_length=20, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='plano',
            name='price',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Preço'),
        ),
    ]
