# Generated by Django 3.2.3 on 2021-06-06 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libercom', '0008_auto_20210605_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='destaque',
            field=models.BooleanField(default=False, verbose_name='Destaque'),
        ),
        migrations.AlterField(
            model_name='testemunho',
            name='enable',
            field=models.BooleanField(default=True, verbose_name='Visivel'),
        ),
    ]
