# Generated by Django 3.2.3 on 2021-06-06 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libercom', '0009_auto_20210606_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='image_name',
            field=models.ImageField(blank=True, upload_to='static/libercom/img/plano'),
        ),
    ]
