# Generated by Django 3.2.3 on 2021-06-06 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('libercom', '0010_plano_image_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plano',
            name='image_name',
        ),
    ]
