# Generated by Django 3.2.3 on 2021-06-06 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libercom', '0011_remove_plano_image_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='plano',
            name='image_name',
            field=models.CharField(blank=True, max_length=40, verbose_name='Nome do arquivo'),
        ),
    ]
